#!/bin/bash

function usage {
    app=`basename $0`
    echo "Usage: $app FILE"
    echo "Play a video using an ASCII-Art renderer (requires mplayer)."
    exit 1
}

if [ $# -lt 1 ]; then
    usage $@
fi

mplayer -quiet -vo aa -monitoraspect 1.3 $1

exit 0
