#!/bin/bash

# UGLY script!
# Update code to replace IFs with a dictionnary lookup 

if [ $# -eq 0 ]; then
	app=`basename $0`
	echo "Usage: $app FILES"
	echo "Replace spaces or accented characters from input files."
	echo "The replacement rules are as follow:"
	echo "  Spaces and commas are replaced by '_'"
	echo "  Accented chars are replaced by their non accented versions"
	echo "  '&' is replaced by \"_and_\""
	echo "Wildcard are allowed, e.g. \"*.txt\"."
	echo "CAUTION: if a target file of the same name already exists,"
	echo "it will be overwritten!"
	exit 1
fi

for i in "$@"; do
	ori=$i
	i=${i//" ",/_}
	i=${i//[éèêë]/e}
	i=${i//çĉ/c}
	i=${i//[üû]/u}
	i=${i//[ïî]/i}
	i=${i//öô/o}
	i=${i//[äàâ]/a}
	i=${i//&/_and_}
	if [ "$i" != "$ori" ]; then
		mv "$ori" "$i"
	fi
done
