#!/bin/bash

if [ $# -eq 0 ]; then
	app=`basename $0`
	echo "Usage: $app FILES"
	echo "Replace spaces or accented characters from input files."
	echo "The replacement rules are as follow:"
	echo "  Spaces and commas are replaced by '_'"
	echo "  Accented chars are replaced by their non accented versions"
	echo "  '&' is replaced by \"_and_\""
	echo "Wildcard are allowed, e.g. \"*.txt\"."
	exit 1
fi

for i in "$@"; do
	ori=$i
	i=${i//" ",/_}
	i=${i//[éèêë]/e}
	i=${i//çĉ/c}
	i=${i//[üû]/u}
	i=${i//[ïî]/i}
	i=${i//öô/o}
	i=${i//[äàâ]/a}
	i=${i//&/_and_}
	if [ "$i" != "$ori" ]; then
		# skip renaming if destination file already exists                   
		if [ -e "$i" ]; then
			echo "Skipping \"$ori\" as \"$i\" already exists!"
		else
			mv "$ori" "$i";
		fi
	fi
done
