#!/bin/bash

# UGLY script!
# Update code to replace IFs with a dictionnary lookup 

if [ $# -ne 1 ]; then
	app=`basename $0`
	echo "Usage: $app FILES"
	echo "Replace spaces or accented characters from input files."
	echo "The replacement rules are as follow:"
	echo "  Spaces and commas are replaced by '_'"
	echo "  Accented chars are replaced by their non accented versions"
	echo "  '&' is replaced by \"_and_\""
	echo "Wildcard are allowed, e.g. \"*.txt\"."
	echo "CAUTION: if a target file of the same name already exists,"
	echo "it will be overwritten!"
	exit 1
fi

for i in $1; do
	dst=${i//" "/_}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//é/e}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//ç/c}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//è/e}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//ü/u}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//ï/i}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//ö/o}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//ë/e}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//â/a}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//à/a}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//,/_}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
	dst=${i//&/_and_}
	if [ "$i" != "$dst" ]; then
		mv "$i" "$dst"
	fi
done
