#!/bin/bash

if [ $# -lt 1 ]; then
	app=$(basename $0)
	echo "Usage: $app dir1 [dir2 ...]" >&2
	echo "Mark directories to be ignored by the Dropbox client." >&2
	exit 1
fi

for i in "$@"; do
	setfattr -n user.com.dropbox.ignored -v 1 "$i"
done
