#!/bin/bash

if [ $# -ne 1 ]; then
	app=`basename $0`
	echo "Usage: $app PATTERN"
	echo "Recursively search all files containing a given PATTERN and print paths."
	echo "Example: f xy => display every file containing the xy sequence."
	exit 1
fi

find . -iname "*$1*" -type f
