#!/bin/bash

if [ $# -ne 1 ]; then
	app=`basename $0`
	echo "Usage: $app PATTERN"
	echo "Recursively search all files or directories containing a given PATTERN and print paths."
	exit 1
fi

find . -iname "*$1*"
