#!/bin/bash

if [ $# -ne 1 ]; then
	app=`basename $0`
	echo "Usage: $app FILE"
	echo "Convert a MKV video file to an H.264 MKV, keeping embedded subtitles."
	echo "The generated output file has the same name as the input, except"
	echo "the filename is postfixed with \"-h264\"."
	echo "Require ffmpeg."
	exit 1
fi

# Does not convert audio, just copy it
input="$1"
ext=${input##*.}
output="${input%%.$ext}-h264.mkv"
ffmpeg -i "$input" -c:a copy -map 0 -c copy -c:v libx264 -crf 23 -preset medium "$output"
