#!/bin/bash

# Extract subtitles of the specified mkv video.
# Note: require mkvmerge from the mkvtoolnix package.

if [ $# -ne 1 ]; then
	app=`basename $0`
	echo "Usage: $app FILE"
	echo "Extract subtitles of the specified video file."
	exit 1
fi

vid_file="$1"
echo "Processing \"$vid_file\""
mkvmerge -i "$vid_file" | grep -i subtitles | awk '{print $3}' | awk -F":" '{print $1}' | while read track_id; do
	subtitle_file="$vid_file"_"$track_id".srt
	echo "    Extracting subtitles at track $track_id"
	mkvextract tracks "$vid_file" "$track_id":"$subtitle_file"
done
