#!/usr/bin/perl -w

# Recursively sort all movies in the current directory by score.
#
# This script assumes movies are named using the following convention:
# title-a.b-xhy.ext
# where:
#   title: title of the movie; make sure there is no dash (-) in the title
#   a.b: score of the movie as defined by IMDB, e.g. 7.8 (see https://www.imdb.com/) 
#   xhy: duration of the movie, e.g. 1h43
#   ext: extension of the movie, e.g. mp4

use strict;
use warnings;

open(my $fh, '-|', 'find . -type f') or die $!;

my %movies = ();

while (my $movie = <$fh>) {
	if ($movie =~ m/(avi$|mkv$|mp4$|mov$|wmv$|flv$)/i) {   # /i for case-unsensitive
		if ($movie =~ /\d\.\d/) {   # matches digit dot digit
			my $score = $&;  # extract match
			#print $movie;
			push(@{$movies{$score}}, $movie);
		}
	}
}

foreach my $score (reverse sort keys %movies) {
	print "\nScore $score:\n";
	foreach (@{$movies{$score}}) {
		print "\t$_";
	}
}

exit 0;
