#!/bin/bash

if [ $# -ne 2 ]; then
	app=`basename $0`
	echo "Usage: $app HEADER FILE"
	echo "Prepend HEADER to FILE."
	exit 1
fi

header=$1
dest=$2
tmp=$app.$$.$RANDOM.tmp

cat $header | cat - $dest > $tmp && mv $tmp $dest
