#!/bin/bash

# Remove all debian packages marked as "rc", i.e. all packages deleted
# from the system but for which configuration files are still present
# Obviously, must be run as root

for i in `dpkg -l|grep ^rc|awk {'print $2'}`;do dpkg --force-all -P $i;done
