#!/bin/bash

state=`synclient|grep Touchpad|awk '{print $3}'`
if [ "$state" = "1" ]; then
	synclient TouchpadOff=0
	#notify-send "Touchpad enabled"
else
	synclient TouchpadOff=1
	#notify-send "Touchpad disabled"
fi
