#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Convert a video file to a H.265 compressed mp4 file"
	echo "Usage: video2h265 QUALITY FILE"
	echo "The generated output file has the same name as the input, except"
	echo "the extension is mp4 and the filename is postfixed with -h265."
	echo "The video codec uses a variable bitrate and the audio is AAC."
	echo "QUALITY must be between 0 (best) and 51 (worst)."
	echo "A quality of 25 seems to be a good default."
	echo "Requires ffmpeg"
	exit 1
fi

# ffmpeg arguments:
# -r   : output framerate (24, 30, etc.)
# -s   : output resolution (hd720, 1280x720, 320x200, etc.)
# -b:v : output bitrate (800k, 1M, etc.)
# -c:v : output video codec (h265, hevc, vp9, etc.)
# ffmpeg -i input.mp4 -b:v 1500k -r 15 -s 320x200 -c:v h265 output.mp4
# -filter_threads n : uses n threads for processing (default to total number of CPUs)
#
# To list all supported codecs by ffmpeg: ffmpeg -codecs

quality=$1
if [ $quality -gt 51 ] || [ $quality -lt 0 ]; then
	echo "Invalid quality value! (must be between 0 and 51)"
	exit 1
fi

# To avoid saturating the system, leave 1 physical CPU for other things
cores=`lscpu|grep "^CPU(s):"|awk -F":" '{print $2}'`
threads_per_core=`lscpu|grep "^Thread(s) per core"|awk -F":" '{print $2}'`
cpus=$((cores/threads_per_core))

if [ $cpus -gt 1 ]; then
	cpus=$((cpus-1))
fi

input="$2"
ext=${input##*.}
output="${input%%.$ext}-h265.mp4"
#ffmpeg -i "$input" -b:v "$bitrate"k -c:v h265 -threads $cpus "$output"
ffmpeg -i "$input" -c:v libx265 -preset medium -crf "$quality" -threads $cpus "$output"
