#!/bin/bash

if [ $# -ne 3 ]; then
	app=`basename $0`
	echo "Usage: $app FILE FROM TO"
	echo "Trim a video by only keeping the specified time window."
	echo "FROM and TO specify the starting and end times for which the video must be kept."
	echo "The example below trims movie.mp4 to only keep content from min 5 and 33 sec to 1 hour, 7 min and 42 sec."
	echo "$app movie.mp4 5:33 1:7:42"
	exit 1
fi

tmp="tmp_$$_$RANDOM_$1"
ffmpeg -i "$1" -ss $2 -to $3 -c:v copy -c:a copy "$tmp" && mv "$tmp" "$1"
