#!/bin/bash

if [ $# -lt 1 ]; then
	app=$(basename $0)
	echo "Usage: $app file1 [file2 ...]" >&2
	echo "Display information about video streams." >&2
	exit 1
fi

for i in "$@"; do
    q=$(ffprobe -hide_banner -i "$i" 2>&1 | grep Video)
    echo "[$i]"
    echo $q
    echo "-------------------------"
done
