#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Convert a video file to a mpeg4 compressed file"
	echo "Usage: video2mpeg4 QUALITY FILE"
	echo "The generated output file has the same name as the input, except"
	echo "the extension is mp4 and the filename is postfixed with -mpeg4."
	echo "The video codec uses a variable bitrate and the audio is AAC."
	echo "QUALITY must be between 1 (best) and 31 (worst)."
	echo "A quality of 4 seems to be a good default."
	echo "Requires ffmpeg"
	exit 1
fi

quality=$1
if [ $quality -gt 31 ] || [ $quality -lt 1 ]; then
	echo "Invalid quality value! (must be between 1 and 31)"
	exit 1
fi

# To avoid saturating the system, leave 1 physical CPU for other things
cores=`lscpu|grep "^CPU(s):"|awk -F":" '{print $2}'`
threads_per_core=`lscpu|grep "^Thread(s) per core"|awk -F":" '{print $2}'`
cpus=$((cores/threads_per_core))

if [ $cpus -gt 1 ]; then
	cpus=$((cpus-1))
fi

input="$2"
ext=${input##*.}
output="${input%%.$ext}-mpeg4.mp4"

fmpeg -i "$input" -c:a copy -c:v libxvid -qscale:v "$quality" -threads $cpus "$output"
