#!/bin/bash
if [ $# -ne 2 ]; then
	echo "Convert a video file to 720P resolution (16:9)."
	echo "Usage: video2_720p BITRATE FILE"
	echo "The generated output file has the same name as the input, except"
	echo "the extension is mp4 and the filename is postfixed with -720p."
	echo "BITRATE is given in KB."
	echo "Require ffmepg"
	exit 1
fi

input="$2"
bitrate="$1"k
ext=${input##*.}
output="${input%%.$ext}-720p.mp4"
ffmpeg -i $input -b:v $bitrate -vf "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2" "$output"
