#!/bin/bash

CPUS=4
RAM=4G
UEFI="-bios /usr/share/ovmf/OVMF.fd"

APP=`basename $0`

function echoerr {
    echo "$@" >&2
}

function usage {
	echoerr "$APP - launch a VM on the specified disk image(s)."
	echoerr "The VM is configured to boot with UEFI, $CPUS CPUs and $RAM of RAM."
    echoerr ""
    echoerr "Usage: $APP -d disk -c iso"
    echoerr "disk    the disk image to use (typically a .qcow file)"
    echoerr "iso     the CD/DVD-ROM image to use (typically an .iso file)"
    echoerr ""
    echoerr "At least one image must be specified."
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

while [[ $# -gt 0 ]]; do
  case $1 in
    -d)
      disk="$2"
      shift # past argument
      shift # past value
      ;;
    -c)
      iso="$2"
      shift # past argument
      shift # past value
      ;;
    *)
      echo "Unknown argument $1"
      exit 1
      ;;
  esac
done

if [ ! -z $disk ]; then
    disk_drive="-drive file=$disk,index=0,media=disk,format=qcow2,if=virtio"
fi

if [ ! -z $iso ]; then
    cdrom_drive="-drive file=$iso,index=1,media=cdrom,format=raw,read-only=on"
fi

# -boot order=d tells QEMU to boot to CDROM first
qemu-system-x86_64 $UEFI -enable-kvm -cpu host -smp cpus=$CPUS -m $RAM -boot order=d $disk_drive $cdrom_drive -vga virtio -device virtio-serial-pci -nic user,model=virtio-net-pci
